### PR TITLE
Bumped some versions in gemspec

### PR DESCRIPTION
**Pull request by hilben**
https://github.com/LawrenceWoodman/mida/issues/11

### CODE REVIEW

**Comment by jcoyne** [comment]
:+1: Please merge @LawrenceWoodman . Also please pass on the maintainership if you're not up to maintaining this anymore.

**Comment by LawrenceWoodman** [comment]
@jcoyne If anyone who wants the responsibility and has sufficient experience and time wants to step forward, I'm happy to give them commit rights to this repo.

**Comment by jcoyne** [comment]
@LawrenceWoodman we over at http://projecthydra.org/ (http://github.com/projecthydra) would be willing to take over maintenance.

**Comment by LawrenceWoodman** [comment]
@jcoyne Wonderful,  I have made you a collaborator.  I have never done it before via github, so let me know if that doesn't work as expected.

**Comment by jcoyne** [comment]
@LawrenceWoodman Can you add me as an author on rubygems too? https://rubygems.org/gems/mida

**Comment by LawrenceWoodman** [comment]
@jcoyne Sure, what email address do you use for rubygems.  Email me it if you don't want to put it in a comment.

**Comment by jcoyne** [comment]
@LawrenceWoodman ﻿justin@curationexperts.com is my rubygems address.

**Comment by LawrenceWoodman** [comment]
@jcoyne Done.  Thanks for taking over the reins.

**Pull request merged**
